version: '3'

services:
  db:
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    env_file:
      - '.env'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --health-interval 10s --health-timeout 5s --health-retries 5"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
    env_file:
      - '.env'

  api:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    ports:
      - '8081:8080'
    volumes:
      - '.:/myapp'
    env_file:
      - '.env'

volumes:
  redis:
  postgres:
