name: Setup
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Install dependent libraries
        run: sudo apt-get install libpq-dev

      - name: Bundle install
        run: |
          gem install bundler -v 2.2.17
          bundle install --jobs 4 --retry 3

      - name: Generate Rails App
        run: |
          docker-compose run api sh
          bundle exec rails new . --api --force --no-deps --database=postgresql
          cp config/database.yml.github-actions config/database.yml
          bundle exec rake db:create
          bundle exec rake db:migrate
        env:
          RAILS_ENV: development
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
